### ISSUE TITLE
sign up page

### ISSUE THREAD

**Issue by Jinnan-Yun** [HyeseonLee/OSS_Hola#19]
TO DO

- [x] 회원가입 정보 입력
- 비밀번호/비밀번호 확인 일치 여부

- [x] 운동 목적 부분 : 데이터 수집

- [x] 회원가입 하기 버튼 누른 후 'main home page' 링크 연결

**Comment by Jinnan-Yun** [comment]
- 나이 입력도 데이터 수집 반영 하는지 체크하기
- 회원가입 완료 후 메세지 팝업?

**Comment by yesjiyoung** [comment]
진난님! signup.html 확인했습니다! 너무 수고많으셨습니다!
다름이 아니라, 현재 back 작업 중 회원가입시 입력되는 정보를 저장하는 회원가입(user)모델을 만들고 있어요! 만드는 도중에 생각이 들었는데
- '운동목적' (중복허용) -> '최근 가장 관심가는 운동'(중복허용X)

으로 변경 부탁드려도 될까요?  마지막에 관심있는 분야를 다 체크하고 그거에 맞게 인기동영상의 default화면을 띄울? 예정인데! 유저입장에서는 여러 개를 투표하고 이를 랜덤으로 솔팅하여 띄워주면 가장 좋긴 하지만 현재 개발단계에서는 유저가 선택한 딱 하나의 관심가는 운동을 화면을 띄우는 것이 좋을 것 같아서요 ~ 이하 추가 의견 남겨주세요! 감사합니다 :)

**Comment by Jinnan-Yun** [comment]
네 그것도 좋은 것 같네요! 그렇게 변경 하겠습니다. 
아 그리고 제가 '닉네임' 부분은 들어가야하는지 정확히 모르겠어서 넣지 않았는데 그 부분도 추가할까요?

**Comment by yesjiyoung** [comment]
네 닉네임 추가해주시면 좋겠습니다!

**Comment by Jinnan-Yun** [comment]
- [x] 닉네임 추가

- [x] 운동 목적(type:중복 허용) --> 최근 가장 관심가는 운동(type:중복 허용 안함)

**Comment by yesjiyoung** [comment]
진난님 수고가 많으십니다!
회원가입 기능과 관려해서 추가적으로 필요한 html말씀드립니다!
-  회원가입이 성공적으로 되었을 때 보여주는 페이지 : signup_correct.html 
- 회원가입이 비정상적으로 되었을 때(비밀번호1 != 비밀번호2 인 경우) 보여주는 페이지 : signup_uncorrect.html 

위의 두 페이지 생성 부탁드립니다! 
(signup_correct_be.html , signup_uncorrect_be.html 참고해보시면 될 것 같아요!)

**Comment by Jinnan-Yun** [comment]
넵 확인했습니다! 이 부분은 이슈 추가로 생성해서 작업 하겠습니다 ~
