### ISSUE TITLE
plan/page layout

### ISSUE THREAD

**Issue by HyeseonLee** [HyeseonLee/OSS_Hola#2]
서비스 페이지 레이아웃 구성과 디자인 작업

**Comment by YuJigun** [comment]
로그인창 구성을 팝업형태, 페이지 내에서 로그인, 새 창 형태 중 어떤걸로 하는게 좋을까요?

**Comment by Jinnan-Yun** [comment]
흠 저는 새 창은 번거로울거 같아서 팝업이나, 페이지 내에서 로그인이 좋을 거 같아요!

**Comment by YuJigun** [comment]
![image](https://user-images.githubusercontent.com/62607197/83631949-56256900-a5d9-11ea-9148-4d7ebd78be03.png)
팝업형태로 진행했어요! ppt 파일 업로드는 슬랙에 해둘까요?

**Comment by Jinnan-Yun** [comment]
> ![image](https://user-images.githubusercontent.com/62607197/83631949-56256900-a5d9-11ea-9148-4d7ebd78be03.png)
> 팝업형태로 진행했어요! ppt 파일 업로드는 슬랙에 해둘까요?

넵 슬랙에 해주세요~

**Comment by Jinnan-Yun** [comment]
회원가입은 페이지 내에서 하도록 만들었고 ppt 슬랙에 업로드 했습니다.
아 그리고 ppt에서 필요한 다른 기본적인 부분들 제가 간단하게 만들었어요!
(+ 슬라이드 노트에 기능 작성)

**Comment by Jinnan-Yun** [comment]
[fitme_page_layout (1).pptx](https://github.com/HyeseonLee/OSS_Hola/files/4808117/fitme_page_layout.1.pptx)

전에 유미님이 슬랙에 올려주신 완성 ppt에서 
1. 기본적으로 다 적용될 페이지 레이아웃
2. 검색창 가운데 정렬
3. 실제로 영상을 보고 운동할 페이지 부분에서 '태그(카테고리)' 삭제 (이 페이지에서는 불필요 하다고 생각이 들었는데 다른분들의 의견이 궁금합니다!)
이 정도만 추가/수정해서 올렸습니다.

**Comment by HyeseonLee** [comment]
back-end 부분에서 작업한 내용은 home_be.html 이런식으로 "_be" 붙여서 templates에 추가해두었습니다. 
front-end에서는 _be 파일 수정은 하지 않아주셨으면 하고, 복사해서 원하시는 html에 붙여 넣어 사용해주시면 감사합니다 !!

**Comment by Jinnan-Yun** [comment]
@HyeseonLee 네 확인했습니다! 혹시 이렇게 공지사항? 같은 부분들 따로 적어두는 곳 만들어 놓으면 어떨까요?!
