### ISSUE TITLE
fitme data 수집

### ISSUE THREAD

**Issue by HyeseonLee** [HyeseonLee/OSS_Hola#25]
영상 data를 수집합니다.
- 영상이름
- 영상코드

due to 6/23 PM 11:59
https://docs.google.com/spreadsheets/d/1xvaBbE12c163pCzQAJZp_K4MmkSfn1RmpbMojjOQcqM/edit?usp=sharing

**Comment by HyeseonLee** [comment]
진난 : 상체, 힙, 푸쉬업(인공지능용으로 쓸 영상 1개)
유미 : 복부, 하체, 플랭크(인공지능용으로 쓸 영상 1개)
지건 : 가슴, 어깨, 런지(인공지능용으로 쓸 영상 1개)
지영 : 등, 팔, 스쿼트(인공지능용으로 쓸 영상 1개)
혜선 : 스트레칭, 다이어트댄스

**Comment by yesjiyoung** [comment]
작업 완료했습니다.
