### ISSUE TITLE
bug/signup 오작동

### ISSUE THREAD

**Issue by HyeseonLee** [HyeseonLee/OSS_Hola#33]
/signup/ url로 접속하여 내용을 채운 후 제출했을 때, 
admin 계정과 동일한 아이디, 패스워드는 회원가입이 안되네요 !
아래와 같은 오류 페이지를 만났습니다.
![image](https://user-images.githubusercontent.com/46919444/85384112-c6d9f880-b57b-11ea-942f-5e3c4b3d7df3.png)

++ admin 계정이 아닌 다른 아이디, 패스워드는 잘 작동합니다.

**Comment by yesjiyoung** [comment]
admin계정과 동일한 아이디, 패스워드는 이미 존재하기 때문에 새로운 회원으로 등록이 안되는게 맞지 않나요 ?

**Comment by HyeseonLee** [comment]
앗 오 그러네요......?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
나중에 시간이 된다면, 유지보수할 때 오류 페이지 말고 다른 화면으로 연결시켜도 좋을 것 같아요~~~

**Comment by yesjiyoung** [comment]
> 앗 오 그러네요......?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
> 나중에 시간이 된다면, 유지보수할 때 오류 페이지 말고 다른 화면으로 연결시켜도 좋을 것 같아요~~~

넵!!
