### ISSUE TITLE
bug/login 오작동

### ISSUE THREAD

**Issue by HyeseonLee** [HyeseonLee/OSS_Hola#34]
정상적으로 회원가입 완료 후 로그인 시도시, 다음과 같은 오류 페이지가 뜹니다ㅠㅠㅠㅠ

![image](https://user-images.githubusercontent.com/46919444/85384577-3e0f8c80-b57c-11ea-9b21-d48c377c4ec7.png)

**Comment by yesjiyoung** [comment]
넵 오류 확인 후 수정했습니다.
수정 내용은 다음과 같습니다.
- login.html - input태그 name 오타 수정
- redirect('home') -> redirect('main')
로그인 시, 메인 화면을 띄워야하기 때문에 redirect('home') 으로 설정해놓았는데, 알고보니 url name이 home이 아니라 main이었습니다 :)

**Comment by HyeseonLee** [comment]
수정 제대로 반영된것 확인했습니다 !! 빠른 수정 감사해요 ㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎㅎ
