### ISSUE TITLE
signup page/function

### ISSUE THREAD

**Issue by Jinnan-Yun** [HyeseonLee/OSS_Hola#58]
회원가입 기능에서 추가적으로 필요한 부분들
TO DO
- [x] signup_correct.html

- [x] signup_uncorrect.html

- 회원가입이 성공적으로 되었을 때 보여주는 페이지 : signup_correct.html
- 회원가입이 비정상적으로 되었을 때(비밀번호1 != 비밀번호2 인 경우) 보여주는 페이지 : signup_uncorrect.html
(signup_correct_be.html , signup_uncorrect_be.html 참고)

**Comment by yesjiyoung** [comment]
signup.html은 지우신건가요.!?

**Comment by Jinnan-Yun** [comment]
signup2.html 로 변경되었습니다..! 죄송합니다ㅠㅠ

**Comment by yesjiyoung** [comment]
[Back-end] 기능 수정 안내드립니다.
- 장고에서 지원하는 user모델의 필드가 부족하다는 생각이 들어, abstractuser 를 imort하여 저희가 원하는 방식으로 custom 하였습니다. ( + nickname, age, workingout ) 
- 모델은 새로운 필드와 함께 완벽하게 구현되었으나, 사용자가 입력하는 input과정에서 radio값을 어떻게 받아와야 할 지.. 그 부분이 해결이 되지 않아 Back-end 회의결과 radio형태로 구현된 age와 workingout을 빼는쪽으로 결정을 하였습니다. 
- nickname은 radio가 아닌 textfield이기 때문에 사용자 입력과정에 문제가 없으나, 댓글을 쓸 때 username으로 간다면 nickname의 필요성을 느끼지 못하여 nickname 필드를 빼기로 결정하였습니다. ( 사실 저는 닉네임으로 구현하고 싶기도 해서.. 이부분은 추후 시간이나면 수정하도록 하겠습니다!)

[Front-end] html 수정 안내드립니다.
- 위의 [Back-end]의 기능 수정과 관련되어 html이 상당부분 변경된 점 양해부탁드립니다.. ㅠ

@Jinnan-Yun 관련 의견 보내주시면 감사드리겠습니다!! :)
